#!/bin/bash

pgrep -x sxhkd >/dev/null || sxhkd &

# multiple monitor setup
#bspc monitor DP1 -d 1 2 3 4 5
#bspc monitor eDP1 -d 6 7 8 9 0
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 4

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

$HOME/.config/polybar/launch.sh
